# Generated by Django 6.1 on 2026-09-05 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_product_discount_price_product_is_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=10, help_text='Kitne items godown me bache hain'),
        ),
    ]
