# Generated by Django 6.0.7 on 2026-08-30 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_department_options_department_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/'),
        ),
        migrations.AddField(
            model_name='category',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Right side image ke liye'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Agar yeh subcategory hai toh parent category select karein (jaise Clothing)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='catalog.category'),
        ),
        migrations.AddField(
            model_name='category',
            name='section_name',
            field=models.CharField(blank=True, default='Categories', help_text="Group heading jaise 'Categories' ya 'Collections'", max_length=100),
        ),
    ]
